### ISSUE TITLE
Boton para abrir el overlay de texto actividad

### ISSUE THREAD

**Issue by agusalex** [agusalex/laboUI#11]
Lo mismo que los botones de vitrinas el boton debe estar siempre en la misma posicion incluso al cambiar la resolucion del dispositivo. idealmente alineado izquierda arriba
![image.png](https://images.zenhubusercontent.com/59b97b2bb0222d5de4779cbc/65fc8c8c-6806-4cac-b8ad-ddf8997eef20)

**Comment by Morzat95** [comment]
Ya está. Ahora lo puse abajo a la izquierda para no interferir con los otros botones que ya están, pero después vemos dónde lo ponemos.
