### ISSUE TITLE
Info Proveta (Pop Up)

### ISSUE THREAD

**Issue by agusalex** [agusalex/laboUI#3]
Pop up al tocar la probeta de su estado
![images](https://user-images.githubusercontent.com/15642727/52655438-edd9e200-2ed2-11e9-97e3-2edb4de527fc.jpeg)

**Comment by Morzat95** [comment]
Ya se generan los popup con la descripción de la probeta. Se puede modificar para mostrar algo mejor pero la funcionalidad está completa.
