### ISSUE TITLE
Boton Vitrina Frascos o Especies

### ISSUE THREAD

**Issue by agusalex** [agusalex/laboUI#9]
Boton que permite abrir una vitrina o la otra, tener encuenta que debe ajustarse a un extremo de la pantalla incluso al cambiar su resolucion.
![image](https://user-images.githubusercontent.com/15642727/52823394-88811f00-3093-11e9-9f97-9a7d4ac3ce84.png)

**Comment by Morzat95** [comment]
Ya está implementado. Faltarían íconos de herramietas de trabajo de laboratorio. Después busco unos cuantos.

**Comment by Morzat95** [comment]
¿No es copia del issue #2 y del #8  ?

**Comment by agusalex** [comment]
Una feature sería la vitrina en si y otra el botón que la abre.
